### ISSUE TITLE
NullPointer Exception when closing TCP connection

### ISSUE THREAD

**Issue by durkode** [LipiLee/ToyShark#3]
Hi,

I have tried this application out, however after setting up the VPN and browsing for a little bit, I am sometimes getting a NullPointer Exception seemingly on trying to close the session. It appears that when attempting to create the fin packet back to the client, the session has already been cleared. Stack trace:

    E/AndroidRuntime: FATAL EXCEPTION: pool-1-thread-4
                  Process: com.lipisoft.toyshark, PID: 2981
                  java.lang.NullPointerException: Attempt to invoke virtual method 'int com.lipisoft.toyshark.network.ip.IPv4Header.getDestinationIP()' on a null object reference
                      at com.lipisoft.toyshark.transport.tcp.TCPPacketFactory.createFinData(TCPPacketFactory.java:112)
                      at com.lipisoft.toyshark.socket.SocketDataReaderWorker.sendFin(SocketDataReaderWorker.java:235)
                      at com.lipisoft.toyshark.socket.SocketDataReaderWorker.readTCP(SocketDataReaderWorker.java:111)
                      at com.lipisoft.toyshark.socket.SocketDataReaderWorker.run(SocketDataReaderWorker.java:56)
                      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                      at java.lang.Thread.run(Thread.java:818)

I haven't had a good look through the code yet, so if you can't patch this yourself let me know if you have any ideas and I can have a look into it.

On another note, I am looking to create an android packet interceptor of sorts and this is the first app I have found that works close to as advertised, so congrats on that.

**Comment by LipiLee** [comment]
@durkode, Thanks for your bug report. I pushed [a patch](https://github.com/LipiLee/ToyShark/commit/30b14d73c74531eb43f0c582a8c42563ee850cec) for it. Please let me know it if you still have this bug after applying the patch.

**Comment by durkode** [comment]
@LipiLee thanks for the patch. That seems to have solved it
